version: '3'
services:
  jump-to-db:
    image: oscarfonts/h2:latest
    container_name: h2-dev
    restart: always
    ports:
      - "1521:1521"
      - "8081:81"
    environment:
      H2_OPTIONS: -ifNotExists
    volumes:
      - /Users/kwanhyunkim/study:/opt/h2-data 